// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Jellyfin.Plugin.PopularTracks.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CorrectedArtistPopularOrderingFeature : object, Xunit.IClassFixture<CorrectedArtistPopularOrderingFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PopularTracks.feature"
#line hidden
        
        public CorrectedArtistPopularOrderingFeature(CorrectedArtistPopularOrderingFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly();
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Corrected artist \"Popular\" ordering", ("  As a Jellyfin listener whose server has no meaningful local play counts\n  I wan" +
                    "t an artist\'s \"Popular\" tracks ordered by real listening popularity\n  So that th" +
                    "e top songs reflect what the world actually plays, not garbage PlayCount"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
            testRunner = null;
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owned tracks are re-ordered by Last.fm popularity")]
        [Xunit.TraitAttribute("FeatureTitle", "Corrected artist \"Popular\" ordering")]
        [Xunit.TraitAttribute("Description", "Owned tracks are re-ordered by Last.fm popularity")]
        public async System.Threading.Tasks.Task OwnedTracksAreRe_OrderedByLast_FmPopularity()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Owned tracks are re-ordered by Last.fm popularity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table1.AddRow(new string[] {
                            "Deep Cut"});
                table1.AddRow(new string[] {
                            "Creep"});
                table1.AddRow(new string[] {
                            "Karma Police"});
#line 7
    await testRunner.GivenAsync("the library has these Radiohead tracks in this order:", ((string)(null)), table1, "Given ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table2.AddRow(new string[] {
                            "Karma Police"});
                table2.AddRow(new string[] {
                            "Creep"});
#line 12
    await testRunner.AndAsync("Last.fm ranks Radiohead\'s top tracks as:", ((string)(null)), table2, "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("the Popular list is built", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table3.AddRow(new string[] {
                            "Karma Police"});
                table3.AddRow(new string[] {
                            "Creep"});
                table3.AddRow(new string[] {
                            "Deep Cut"});
#line 17
    await testRunner.ThenAsync("the tracks appear in this order:", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tracks unknown to Last.fm fall to the bottom keeping their original order")]
        [Xunit.TraitAttribute("FeatureTitle", "Corrected artist \"Popular\" ordering")]
        [Xunit.TraitAttribute("Description", "Tracks unknown to Last.fm fall to the bottom keeping their original order")]
        public async System.Threading.Tasks.Task TracksUnknownToLast_FmFallToTheBottomKeepingTheirOriginalOrder()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tracks unknown to Last.fm fall to the bottom keeping their original order", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table4.AddRow(new string[] {
                            "B-side One"});
                table4.AddRow(new string[] {
                            "Hit Single"});
                table4.AddRow(new string[] {
                            "B-side Two"});
#line 24
    await testRunner.GivenAsync("the library has these Radiohead tracks in this order:", ((string)(null)), table4, "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table5.AddRow(new string[] {
                            "Hit Single"});
#line 29
    await testRunner.AndAsync("Last.fm ranks Radiohead\'s top tracks as:", ((string)(null)), table5, "And ");
#line hidden
#line 32
    await testRunner.WhenAsync("the Popular list is built", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "title"});
                table6.AddRow(new string[] {
                            "Hit Single"});
                table6.AddRow(new string[] {
                            "B-side One"});
                table6.AddRow(new string[] {
                            "B-side Two"});
#line 33
    await testRunner.ThenAsync("the tracks appear in this order:", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CorrectedArtistPopularOrderingFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CorrectedArtistPopularOrderingFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
